### ISSUE TITLE
\mathcal{} symbols like chi-square are not rendered properly

### ISSUE THREAD

**Issue by marcora** [betanalpha/knitr_case_studies#50]
\mathcal{} symbols like chi-square are not rendered properly in html. They appear as an empty rectangles in a web browser.

**Comment by betanalpha** [comment]
Can you offer any detailed locations where these issues arise?  I don't see any issues on my end but I'm also not sure where to look.

**Comment by marcora** [comment]
For example...

![Slide1](https://github.com/user-attachments/assets/b3c9cf76-6ea7-4f31-ab7c-31e84d445f13)

**Comment by betanalpha** [comment]
Interesting.  It renders fine for me, see the attached image, so I wonder if the HTML is somehow directing you to a misbehaving MathJax server.

<img width="825" alt="typesetting_example" src="https://github.com/user-attachments/assets/1df821f9-3dba-400d-ab0e-ea63e2f554ac">

I am going to close this issue because this chapter has been superseded by the newer chapters listed under "Part I: Probability Theory" at https://betanalpha.github.io/writing/.  The newer chapters use KaTeX instead of MathJax which might help avoid issues, but if you're still seeing problems then don't hesitate to open an issue in that repository.

Thanks!

**Comment by marcora** [comment]
Thanks! Looking forward to reading the updated articles
